services:
  auth-service:
    environment:
      # - FRONTEND_URL=https://tobarumg.lat
      # - CORS_ORIGIN=https://tobarumg.lat
      # - GITHUB_CALLBACK_URL=https://tobarumg.lat/api/auth/github/callback
      # Local Dev overrides
      - GOOGLE_CLIENT_ID=247839127716-o9jqchaocpbdl7lf1sli9v0prrpp4c1c.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - SESSION_COOKIE_SECURE=false
      - SESSION_COOKIE_SAMESITE=lax
      - SESSION_COOKIE_DOMAIN=
      - FRONTEND_URL=https://tobarumg.lat
      - CORS_ORIGIN=https://tobarumg.lat
      - GOOGLE_CALLBACK_URL=https://tobarumg.lat/api/auth/google/callback
      - FACEBOOK_CALLBACK_URL=https://tobarumg.lat/api/auth/facebook/callback
      - GITHUB_CALLBACK_URL=https://tobarumg.lat/api/auth/github/callback
    dns:
      - 8.8.8.8
      - 1.1.1.1

  api:
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:4200,https://tobarumg.lat,https://www.tobarumg.lat
